// demo/vite-vue/src/App.vue
<script setup>
import { test } from './dataprotector';
</script>

<template>
  <header>
    <img
      alt="Vue logo"
      class="logo"
      src="./assets/logo.svg"
      width="125"
      height="125"
    />
    <div>
      <button @click="test">TEST</button>
      <p>Open the console to see logs</p>
    </div>
  </header>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }
}
</style>

// packages/demo/vite-react/src/App.tsx
import './App.css';
import { test } from './dataprotector';

function App() {
  return (
    <>
      <img
        alt="React logo"
        className="logo"
        src="/react.svg"
        width="100"
        height="100"
      />
      <div>
        <button
          onClick={() => {
            test().catch(console.log);
          }}
        >
          TEST
        </button>
        <p>Open the console to see logs</p>
      </div>
    </>
  );
}

export default App;
