// packages/demo/vite-react/src/App.tsx
import { useState } from 'react';
import './App.css';
import { createProtectedData } from './dataprotector';

function App() {
  const [isLoading, setIsLoading] = useState(false);

  return (
    <>
      <img
        alt="React logo"
        className="logo"
        src="/react.svg"
        width="100"
        height="100"
      />
      <div>
        <button
          disabled={isLoading}
          onClick={() => {
            setIsLoading(true);
            createProtectedData()
              .then(() => {
                setIsLoading(false);
                console.log('DONE');
              })
              .catch((err) => {
                setIsLoading(false);
                console.error(err);
              });
          }}
        >
          Create protected data
        </button>
        <p>Open the console to see logs</p>
      </div>
    </>
  );
}

export default App;

// packages/demo/vite-vue/src/App.vue
<script setup>
import { ref } from 'vue';
import { createProtectedData } from './dataprotector';

const isLoading = ref(false);

function protectData() {
  isLoading.value = true;
  createProtectedData()
    .then(() => {
      isLoading.value = false;
      console.log('DONE');
    })
    .catch((err) => {
      isLoading.value = false;
      console.error(err);
    });
}
</script>

<template>
  <div>
    <img
      alt="Vue logo"
      class="logo"
      src="./assets/logo.svg"
      width="100"
      height="100"
    />
    <div>
      <button :disabled="isLoading" @click="protectData">
        Create protected data
      </button>
      <p>Open the console to see logs</p>
    </div>
  </div>
</template>

<style scoped>
.logo {
  display: block;
  margin: 0 auto 2rem;
}
</style>
