// packages/demo/create-react-app-ts/src/App.tsx
import { useState } from 'react';
import { createProtectedData } from './dataprotector';

const App = () => {
  const [isLoading, setIsLoading] = useState(false);

  return (
    <div style={{ textAlign: 'center' }}>
      <h1>
        dataprotector-sdk with
        <br />
        Create React App (TypeScript)
      </h1>
      <div style={{ marginTop: '20px' }}>
        <img src="/logo192.png" width="100" alt="React logo" />
      </div>
      <button
        style={{ marginTop: '20px' }}
        disabled={isLoading}
        onClick={() => {
          setIsLoading(true);
          createProtectedData()
            .then(() => {
              setIsLoading(false);
              console.log('DONE');
            })
            .catch((err) => {
              setIsLoading(false);
              console.error(err);
            });
        }}
      >
        Create protected data
      </button>
      <p>Open the console to see logs</p>
    </div>
  );
};

export default App;

// packages/demo/vite-vue/src/App.vue
<script setup>
import { ref } from 'vue';
import { createProtectedData } from './dataprotector';

const isLoading = ref(false);

function protectData() {
  isLoading.value = true;
  createProtectedData()
    .then(() => {
      isLoading.value = false;
      console.log('DONE');
    })
    .catch((err) => {
      isLoading.value = false;
      console.error(err);
    });
}
</script>

<template>
  <div>
    <img
      alt="Vue logo"
      class="logo"
      src="./assets/logo.svg"
      width="100"
      height="100"
    />
    <div>
      <button :disabled="isLoading" @click="protectData">
        Create protected data
      </button>
      <p>Open the console to see logs</p>
    </div>
  </div>
</template>

<style scoped>
.logo {
  display: block;
  margin: 0 auto 2rem;
}
</style>
