// demo/react-js/src/App.js
import "./App.css";
import { IExecDataProtector } from "dataprotector-sdk";
import { useEffect } from "react";

// type ProtectedData = {
//   datasetChecksum: string;
//   datasetMultiaddr: string | Buffer;
//   datasetName: string;
//   owner: string;
//   schema: JSON;
// };

function App() {
  let iexecDataProtector = null;

  let ethProvider = null;
  const connection = async () => {
    if (window.ethereum) {
      console.log("using default provider");
      ethProvider = window.ethereum;
      ethProvider.on("chainChanged", (_chainId) =>
        window.location.reload()
      );
      ethProvider.on("accountsChanged", (_accounts) =>
        window.location.reload()
      );
      await window.ethereum.request({
        method: "eth_requestAccounts",
      });
      window.ethereum.request({
        method: "wallet_addEthereumChain",
        params: [
          {
            chainId: "0x86",
            chainName: "iExec Sidechain",
            nativeCurrency: {
              name: "xRLC",
              symbol: "xRLC",
              decimals: 18,
            },
            rpcUrls: ["https://bellecour.iex.ec"],
            blockExplorerUrls: ["https://blockscout-bellecour.iex.ec"],
          },
        ],
      });
    } else {
      console.log("no provider");
    }
  };

  useEffect(() => {
    if (window.ethereum !== undefined) {
      iexecDataProtector = new IExecDataProtector(window.ethereum);
    }
  }, [ethProvider]);

  const testFetch = async () => {
    console.log("Wait for the creation of the CNFT... ! It's Loading... ");
    // const data: ProtectedData[] = await iexecDataProtector!.fetchProtectedData({
    //   requireSchema: {
    //     nom: "string",
    //     prenom: "string",
    //     pokerLicense: "string",
    //   },
    // });
    // data.map((d) => {
    //   console.log(d);
    // });
  };

  return (
    <div className="App">
      <header className="App-header">
        <button onClick={connection}>Connection</button>
        <br />
        <button onClick={testFetch}>testFetch</button>
        <br />
      </header>
    </div>
  );
}

export default App;

// demo/vue-project/src/App.vue
<script setup>
import HelloWorld from './components/HelloWorld.vue';
import TheWelcome from './components/TheWelcome.vue';
import { IExecDataProtector } from 'dataprotector-sdk';
let iexecDataProtector = null;

let ethProvider = null;
const connection = async () => {
  if (window.ethereum) {
    console.log('using default provider');
    ethProvider = window.ethereum;
    ethProvider.on('chainChanged', (_chainId) => window.location.reload());
    ethProvider.on('accountsChanged', (_accounts) => window.location.reload());
    await window.ethereum.request({
      method: 'eth_requestAccounts',
    });
    window.ethereum.request({
      method: 'wallet_addEthereumChain',
      params: [
        {
          chainId: '0x86',
          chainName: 'iExec Sidechain',
          nativeCurrency: {
            name: 'xRLC',
            symbol: 'xRLC',
            decimals: 18,
          },
          rpcUrls: ['https://bellecour.iex.ec'],
          blockExplorerUrls: ['https://blockscout-bellecour.iex.ec'],
        },
      ],
    });
  } else {
    console.log('no provider');
  }
};
connection();
iexecDataProtector = new IExecDataProtector(window.ethereum);
</script>

<template>
  <header>
    <img
      alt="Vue logo"
      class="logo"
      src="./assets/logo.svg"
      width="125"
      height="125"
    />

    <div class="wrapper">
      <HelloWorld msg="You did it!" />
    </div>
  </header>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>
